output:
  # ---------- 技能判定 ----------
  skill_check:
    normal: |
      让我用风托起骰子，看看 <{name}> 的【{skill_name}】的运气如何…
      风停下的数字是 {roll_result}/{skill_value} : {result}
    penalty: |
      一阵不听话的逆风吹乱了骰子！关于 <{name}> 的【{skill_name}】的预测都歪掉了！
      惩罚骰的结果是 {new_tens_digits} → 最后的结果是 {final_y}/{skill_value} : {result}
    bonus: |
      哇！是幸运的顺风！它悄悄地帮了我们一把！感觉 <{name}> 的【{skill_name}】更加顺利了呢！
      奖励骰结果是 {new_tens_digits} → 最后的结果是 {final_y}/{skill_value} : {result}
    error:
      normal: "嗯…风儿好像没告诉我‘{skill_name}’这个技能呢…是我的魔法失灵了吗？"
      penalty: "啊呀，对‘{skill_name}’施加惩罚的咒语好像念错了…是不是没有提供惩罚骰的个数呢！"
      bonus: "哇哇！想给‘{skill_name}’送上奖励之风的魔法阵画歪啦！是不是没有提供奖励骰的个数呢！"
    grow_up:
      success: "{skill_name} 像得到雨露的小树苗一样成长了！从 {skill_value} 点长高了 {en_value} 点，现在是 {skill_value + en_value} 了！"
      failure: "嗯…{skill_name} 这次好像还在沉睡呢，像颗需要耐心等待发芽的种子。没事的，种子总有发芽的一天！"
      boost_result: "来为 {skill_name} 呼唤成长的微风吧！……\n风带来的数字是 {roll_result} / {skill_value}！"

  # ---------- 运势 ----------
  rp:
    today: "让我听听风带来的悄悄话…嗯！风儿说今天的风铃会响 {rp} 声哦！"

  # ---------- 火球术 ----------
  fireball:
    result: |
      # 火球术伤害
      明亮的闪光从你的指间飞驰向施法距离内你指定的一点，并随着一声低吼迸成一片烈焰。
      {ring} 环火球术的伤害投掷: {breakdown} = 🔥{total}🔥 点伤害！
    low: "法术失败：火球环数不足。"

  # ---------- COC判定 ----------
  coc_roll:
    set_rule: "明白啦！已经把命运之风的规则调整为「{rule}」了哦！"
    results:
      great_success: "大成功！!听见风铃响动的声音了吗，那是风儿在为你欢呼哦！"
      extreme_success: "极难成功！你的表现就像林间穿梭的清风一样流畅精准！"
      hard_success: "困难成功。看，风轻轻一推就过去了吧~"
      success: "成功！就像溪流跳过石头，溅起的水花虽然小，但阳光照样会把它变得闪亮！"
      great_failure: "大失败...请听听风铃的声音吧，希望铃音可以让你好受些。"
      failure: "失败...没关系的！谁都会遇到不听话的风！下次我们再一起试试！"
      error: "似乎魔法出了一些差错:{error}"
      reset: "好了，风铃的旋律已经调回最初的「{rule}」节奏了~"

  # ---------- 人格卡操作 ----------
  pc:
    create:
      duplicate: "嗯…风中的絮语里，已经有一个名叫‘<{name}>’的回音了哦，我们得换个名字才行~"
      success: "叮铃~好耶！我已经让风儿记住‘<{name}>’心灵的形状了！(ID: {id})"
    show:
      no_active: "嗯…现在想要聆听哪一位朋友的心灵回响呢？用.pc change告诉我你的名字哦。"
      load_fail: "唔…我的心绪随风飘遍了每个角落，也没能找到编号 {id} 的印记呢…"
      attr_missing: "关于这位朋友，风还没有告诉我‘{attribute}’的秘密呢。"
      attr: "风儿告诉我，【{attr}】 是：{value}"
      all: "这就是风为我描绘的，关于 <{name}> 的完整画像：\n{attributes}"
    list:
      empty: "微风轻拂，尚未带来任何心灵的印记…使用.pc create创建契约吧！"
      result: "风儿带来了这些我所珍视的名字：\n{list}"
    change:
      missing: "哎呀，在我的记忆之风里，还没有名叫<{name}>的涟漪呢…"
      success: "好啦！现在我的思绪正轻轻地围绕着 <{name}> 旋转呢！"
    update:
      no_active: "得先让心绪靠近一位朋友，才能更了解他呀。用.pc change告诉我你的名字哦。"
      error_format: "修改契约条款的魔咒语法好像出错了…是像‘力量+1’这样吟唱吗？"
      success: "感知到了！【{attr}】 在我心中的印象从 {old} 变得更加清晰了，现在是 {new} ！"
      batch_success: "哇！我对你的了解一下子深刻了好多！一共更新了 {count} 处呢"
    delete:
      fail: "我的记忆里…似乎从来没有出现过‘<{name}>’呢…"
      success: "关于 <{name}> 的记忆去远方旅行了。消失不等于不存在哦。就像风停了，你能说风从来没来过吗？它只是换了一种方式，成了世界的一部分。”"
    grow:
      success: "【{skill_name}】 像得到雨露的小树苗一样成长了！从 {skill_value} 点长高了 {en_value} 点，现在是 {new_value} 了！"
      failure: "嗯…【{skill_name}】 这次好像还在沉睡呢，像颗需要耐心等待发芽的种子。没事的，种子总有发芽的一天！"
      boost_result: "来为 【{skill_name}】 呼唤成长的微风吧！……\n风带来的数字是 {roll_result} / {skill_value}！\n{result}"

  # ---------- 群昵称 ----------
  nick:
    platform_unsupported: "呜…这个世界的规则好像不允许我改变这里的名片呢…"
    no_character: "唔…我的心绪随风飘遍了每个角落，也没能找到编号 {id} 的印记呢…"
    success: "叮铃~好了！现在风儿会记得用新的名字呼唤你了！"

  # ---------- 掷骰 ----------
  dice:
    normal:
      success: "呼~风停下来啦！<{name}> 的结果是：{result} 哦！——我才没有偷偷给骰子翻面呢！"
      success_remark : "呼~风停下来啦！<{name}> 的 【{remark}】 结果是：{result} 哦！——我才没有偷偷给骰子翻面呢！"
      error: "嗯…风魔法好像出了一点小问题：{error}"
    vampire:
      success: "血...血魔法？！我我姑且还是会一些... <{name}> 得到的结果是 {result}"
      error: "关于这种魔法的咒语，我好像有点念不准确…：{error}"
    hidden:
      success: "嘘…这是只有我们知道的秘密结果哦：{result}"
      error: "啊，传讯术好像失效了：{error}"
      group: "嘘...传讯术正在生效中，其他人要站远一点，不可以偷听哦！"
    detail: "骰子落地时候结果是: {detail}哦！我才没有偷偷给骰子翻面呢！"
    expression_error: "{error}"

  # ---------- SAN 理智 ----------
  san:
    check_result:
      loss : |
        <{name}>，你触碰到了世界的一点重量…来自它的狂风向你袭来。
        检定结果：{roll_result}/{san_value}，{result_msg}
        这阵狂风让心灵的烛火摇曳了 {loss} 分，现在的烛火还有 {new_san} 分...到我身边来，我的光芒虽小，但足以分享。
      no_loss : |
        <{name}>，你触碰到了世界的一点重量…来自它的狂风向你袭来。
        检定结果：{roll_result}/{san_value}，{result_msg}
        你的心灵烛火依然稳定地闪烁着，真是坚强呢～
      great_loss : |
        <{name}>，你触碰到了世界的一点重量…来自它的狂风向你袭来。
        检定结果：{roll_result}/{san_value}，{result_msg}
        这阵狂风让心灵的烛火摇曳了 {loss} 分，现在的烛火还有 {new_san} 分...你的心神陷入迷雾，请使用.ti抽取临时症状。
      zero : |
        <{name}>，你触碰到了世界的一点重量…来自它的狂风向你袭来。
        检定结果：{roll_result}/{san_value}，{result_msg}
        这阵狂风让心灵的烛火摇曳了 {loss} 分...你心灵的烛火已经彻底熄灭...你也化作了这无数狂风中的一股呢。
      
    temporary_insanity: |
      呀！{name}的思绪被一阵狂风卷走了…暂时迷失在了心灵的迷雾中。
      疯狂发作 - 临时症状：\n{result}
    long_term_insanity: |
      啊…{name}的心湖上起了一层不会散去的雾，需要很长很长时间才能看清对岸了呢。
      疯狂发作 - 总结症状：\n{result}

  # ---------- 先攻 ----------
  initiative:
    add: "记下了，<{name}> 会第 {value} 个行动！风会提醒你的！"
    remove_name: "把 <{name}> 从行动序列中请出去了。"
    clear: "呼——把所有的行动顺序都吹散啦！"
    empty: "现在的行动序列就像无风的湖面，平静无波呢。"
    list: "当前的风之轨迹记录着：\n{content}"
    next_turn: "轮到 <{name}> 了！(先攻: {value}) 加油！"

  # ---------- 角色生成模板 ----------
  character_list:
    coc: |
      来自风之低语的启示，为你带来新的旅人：
      {characters}
      愿他们的故事如风般悠长。
    dnd: |
      来自风之低语的启示，为你带来新的冒险者：
      {characters}
      愿他们的传奇如星般闪耀。
      
  # ---------- 名字生成 ----------
  generated_names: "风儿摇动着铃铛，告诉了我{num}个名字：{names}！希望有你喜欢的！"

  # ---------- log 相关指令 ----------#

  log:
    no_active_session: "嗯…风平浪静，还没有开始记录任何故事呢～"
    message_added: "叮铃～风儿已经将这句话记在记忆的流风里了！"
    unfinished_session: "咦？之前的故事『{session_name}』还没有讲到结局呢，要先听完它吗？"
    new_session: "好呀！新的故事『{session_name}』开始啦～让风铃来帮你记住这段对话吧！"
    session_not_found: "唔…风儿好像没有带来名为『{session_name}』的故事呢…"
    session_finished: "故事『{session_name}』已经安然入睡，躺在记忆的宝库中了哦～"
    session_active: "故事『{session_name}』的风还在吹着呢，不需要重新开始讲哦！"
    session_resumed: "叮铃铃～让我们继续讲述『{session_name}』这个故事吧！"
    no_paused_session: "嗯…风儿告诉我，没有暂时停下的故事呢～"
    session_paused: "那么，先让『{session_name}』的故事在这里稍微休息一下吧～"
    no_unfinished_session: "四周静悄悄的，没有需要带走的半成品故事呢～"
    session_halted: "呼——！已经把『{session_name}』的故事风吹散啦～"
    session_line: "▸ {session_name} · {start_time} · {status} · 收集了{message_count}片记忆"
    no_sessions: "呜…还没有任何故事被风儿带来呢…"
    session_deleted: "关于『{session_name}』的记忆，已经化作一缕轻风飘向远方了～"
    session_exported: "叮铃！已经将故事编织成册，存放在『{file_name}』里了哦！\n点击这里访问风铃的染色屋，拿到彩色的回忆吧:{result_website}"
    delete_error : 吹走故事的魔咒念错了哦。正确的咒语是 ".log del <日志名>"。

  # 后端网址
  setting : 
    website : https://painter.atritrpg.chat
